### ISSUE TITLE
최근 올라온 소식(메인페이지)에서 불러와 보여주기

### ISSUE THREAD

**Issue by astrod** [NHNNEXT/2014-03-DEVWEB-RUWORKING#34]
메인페이지로 데이터를 불러와서 집어 넣는다.

**Comment by hataeho1** [comment]
게시글 수정시 동일 게시물이 중복 표시되는 문제가 있습니다

**Comment by hataeho1** [comment]
게시물 본문에 대한 길이 제약이 적용되어 있는데 제목부분에 대해서도 적용될 필요가 있어 보입니다. 사용자가 제목을 길게 작성했을 경우 Layout이 깨질 가능성이 있어 보입니다
